/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "calculation.pb-c.h"
void   calculation__init
                     (Calculation         *message)
{
  static Calculation init_value = CALCULATION__INIT;
  *message = init_value;
}
size_t calculation__get_packed_size
                     (const Calculation *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &calculation__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t calculation__pack
                     (const Calculation *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &calculation__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t calculation__pack_to_buffer
                     (const Calculation *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &calculation__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Calculation *
       calculation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Calculation *)
     protobuf_c_message_unpack (&calculation__descriptor,
                                allocator, len, data);
}
void   calculation__free_unpacked
                     (Calculation *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &calculation__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor calculation__field_descriptors[4] =
{
  {
    "left",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Calculation, left),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "operation",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Calculation, operation),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "right",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Calculation, right),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pid",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Calculation, pid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned calculation__field_indices_by_name[] = {
  0,   /* field[0] = left */
  1,   /* field[1] = operation */
  3,   /* field[3] = pid */
  2,   /* field[2] = right */
};
static const ProtobufCIntRange calculation__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor calculation__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Calculation",
  "Calculation",
  "Calculation",
  "",
  sizeof(Calculation),
  4,
  calculation__field_descriptors,
  calculation__field_indices_by_name,
  1,  calculation__number_ranges,
  (ProtobufCMessageInit) calculation__init,
  NULL,NULL,NULL    /* reserved[123] */
};
